export type {
  Result,
  SupportIssuePayload,
  SupportSubmissionCategory,
  SupportSubmissionContext,
  SupportSubmissionIssueInput,
  SupportSubmissionPayload,
  SupportSubmissionPriority,
} from "@repo/core";
export {
  buildSupportIssueMarkdownBody,
  buildSupportIssuePayload,
  buildSupportIssueTitle,
  createDynamicCodeFence,
  getSupportIssueLabels,
  MAX_ACTUAL_OUTCOME_LENGTH,
  MAX_EXPECTED_OUTCOME_LENGTH,
  MAX_ISSUE_TITLE_LENGTH,
  MAX_MESSAGE_LENGTH,
  MAX_REPRODUCTION_STEPS_LENGTH,
  MAX_SUBJECT_LENGTH,
  SupportSubmissionCategorySchema,
  SupportSubmissionContextSchema,
  SupportSubmissionIssueInputSchema,
  SupportSubmissionPayloadSchema,
  SupportSubmissionPrioritySchema,
  sanitizeTitleText,
  wrapUntrustedContent,
} from "@repo/core";
